# Generated by Django 5.1.1 on 2024-10-17 07:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0004_productattribute_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'En préparation'), (1, 'Passée'), (2, 'Reçue')], default=0)),
                ('date_commande', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ht',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ttc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AlterField(
            model_name='productitem',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='product_item', to='monapp.productattributevalue'),
        ),
        migrations.CreateModel(
            name='CommandeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandeitems', to='monapp.commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.fournisseurs'),
        ),
        migrations.CreateModel(
            name='ProductFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix unitaire HT')),
                ('price_ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix unitaire TTC')),
                ('stock', models.IntegerField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date création')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.fournisseurs')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.product')),
            ],
            options={
                'unique_together': {('product', 'fournisseur')},
            },
        ),
    ]
